"""
KnowledgeRepository + FileStoragePort (docs/versions/05, §7) — чистый CRUD,
без собственных use case'ов; команды, которые этим управляют, — в
application/admin/ (docs/versions/03, §5).
"""

from __future__ import annotations

from typing import Protocol

from dekoder.domain.knowledge_base.case import KnowledgeCase
from dekoder.domain.knowledge_base.document import KnowledgeDocument
from dekoder.shared.domain.identifiers import CaseId, DocumentId


class KnowledgeRepository(Protocol):
    def add_document(self, document: KnowledgeDocument) -> None: ...

    def update_document(self, document: KnowledgeDocument) -> None: ...

    def delete_document(self, document_id: DocumentId) -> None: ...

    def get_document(self, document_id: DocumentId) -> KnowledgeDocument | None: ...

    def list_documents(self) -> list[KnowledgeDocument]: ...

    def add_case(self, case: KnowledgeCase) -> None: ...

    def update_case(self, case: KnowledgeCase) -> None: ...

    def archive_case(self, case_id: CaseId) -> None: ...

    def get_case(self, case_id: CaseId) -> KnowledgeCase | None: ...

    def list_cases(self) -> list[KnowledgeCase]: ...

    def link_document_to_case(self, document_id: DocumentId, case_id: CaseId) -> None: ...

    def unlink_document_from_case(self, document_id: DocumentId, case_id: CaseId) -> None: ...

    def list_documents_for_case(self, case_id: CaseId) -> list[DocumentId]: ...


class FileStoragePort(Protocol):
    def save(self, document_id: DocumentId, content: bytes) -> None: ...

    def read(self, document_id: DocumentId) -> bytes: ...

    def delete(self, document_id: DocumentId) -> None: ...
